### ISSUE TITLE
speechbrain library

### ISSUE THREAD

**Issue by baselebido** [Ubenwa/cryceleb2023#3]
i am trying to use your code for my project but speechbrain library doesn't satisfied to download, the following is the error message.
note: i used also virtual environment but it didn't works.

error message: 
Collecting speechbrain
  Using cached speechbrain-0.5.16-py3-none-any.whl.metadata (23 kB)
Collecting hyperpyyaml (from speechbrain)
  Using cached HyperPyYAML-1.2.2-py3-none-any.whl.metadata (7.6 kB)
Collecting joblib (from speechbrain)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from speechbrain) (1.26.3)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from speechbrain) (23.2)
Collecting scipy (from speechbrain)
  Using cached scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting sentencepiece (from speechbrain)
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-uiev7mk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-uiev7mk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires   
          self.run_setup()
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-uiev7mk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\HP\AppData\Local\Temp\pip-build-env-uiev7mk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
----------------------------------------------------------------------------------------------

and i used Visual Studio code to run it

**Comment by gorinars** [comment]
is this happening when you do `pip install speechbrain`?

I have not seen this error before but it's been forever since last time I used windows

**Comment by baselebido** [comment]
Yes this happening when i  do pip install speechbrain

**Comment by gorinars** [comment]
From logs it appears that you use python 3.12. I can suggest a few things:
- try using an older python version (I can confirm speechbrain is OK with 3.10)
- update pip
if none helps, perhaps ask in [speechbrain community](https://github.com/speechbrain/speechbrain)

**Comment by baselebido** [comment]
ok, after running the code, how i can know the result of baby crying

**Comment by gorinars** [comment]
It is not quite clear which code you are running. I would suggest to start with our [notebook to evaluate a pre-trained mode](https://colab.research.google.com/github/Ubenwa/cryceleb2023/blob/main/evaluate.ipynb)l

**Comment by baselebido** [comment]
i run the evaluate model, but i didn't see the result why the baby is
crying like(hungry, discomfortable ...), and i didn't understand what is
period (B. D) for babies voices,
can you help me what should i do to see the results.
here is my output
[image: WhatsApp Image 2024-01-29 at 6.04.37 PM.jpeg]


‫في الأحد، 28 يناير 2024 في 9:30 م تمت كتابة ما يلي بواسطة ‪Arseniy Gorin‬‏
***@***.***‬‏>:‬

**Comment by baselebido** [comment]
i run the evaluate model, but i didn't see the result why the baby is crying like(hungry, discomfortable ...), and i didn't understand what is period (B. D) for babies voices,
can you help me what should i do to see the results.

**Comment by gorinars** [comment]
Sorry but CryCeleb data does not have labels like hungry, discomfort, etc. It is intended for verification challenge.

Please see detailed description of data and challenge in the [paper](https://arxiv.org/abs/2305.00969)
